### ISSUE TITLE
[💡Question] 2주차_p71_인덱스 스캔 효율화 튜닝의 방법

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-tuning-level-up#10]
### ❓이런 내용이 궁금해요.

>

인덱스 스캔 효율화 튜닝의 방법으로 더 많은 예시가 있었으면 좋을것 같습니다! (정렬을 통한 방법밖에 없나요?)

**Comment by dlrjs2360** [comment]
인덱스 스캔 과정에서 발생하는 비효율을 줄이는 방법은 정렬 외에 `인덱스 파티셔닝`이 있습니다.

### 인덱스 파티셔닝(Index Partitioning)
DBMS에서 파티셔닝은 말 그대로 여러 파티션으로 나누어 저장하는 것으로 테이블을 파티션으로 나눌 수도 있고 인덱스를 파티션으로 나눌 수도 있습니다. 당연하게도 그 중 인덱스를 파티션으로 나누는 것이 인덱스 파티셔닝입니다.

뤼튼에게 예시를 부탁하여 한 가지 가져와봤습니다.
```sql
CREATE TABLE sales (
    sale_id INT,
    sale_date DATE,
    amount DECIMAL(10, 2),
    customer_id INT
);

CREATE INDEX sales_date_idx ON sales(sale_date)
PARTITION BY RANGE (sale_date) (
    PARTITION p202301 VALUES LESS THAN ('2023-02-01'),
    PARTITION p202302 VALUES LESS THAN ('2023-03-01'),
    PARTITION p202303 VALUES LESS THAN ('2023-04-01'),
    PARTITION p202304 VALUES LESS THAN ('2023-05-01')
    -- 추가 파티션을 계속 추가할 수 있습니다.
);
```

위와 같이 테이블에 대한 인덱스를 생성할 때 파티션을 나눌 수 있습니다.

이제 아래와 같은 SQL로 조회를 한다고 하면
```sql
SELECT * FROM sales
WHERE sale_date >= '2023-03-01' AND sale_date < '2023-04-01';
```

이 쿼리는 sale_date가 2024년 3월에 해당하는 데이터만 선택하므로 데이터베이스는 p202303 파티션만 선택하여 스캔합니다.

만약 전체 인덱스가 300개이고 10개의 파티션으로 나뉘었다면 300개 중 30개의 인덱스 리프 블록만 탐색하게 되므로 효율성이 크게 향상될 수 있습니다.

또한, 테이블과 인덱스가 모두 파티셔닝 된 상태(=로컬 파티셔닝)가 이루어지면 파티션 단위로 인덱스를 재생성하고 관리할 수 있기 때문에 데이터 입력 또한 빠르게 수행할 수 있습니다.

이 파티셔닝은 테이블과 인덱스의 파티셔닝 유무에 따라 다양한 종류로 나누어 집니다.

< 파티셔닝 되지 않은 테이블 + 파티셔닝 된 인덱스 >
![image](https://github.com/code-appender/sql-tuning-level-up/assets/81156109/9b19fe3e-86b8-4760-9eb9-72c2c342e9c3)

< 파티셔닝 된 테이블 + 파티셔닝 된 인덱스 > 
![image](https://github.com/code-appender/sql-tuning-level-up/assets/81156109/d56be74b-19cd-4c54-8cc1-b43664d81850)

이 외에도 여러 구조가 있으며 장단점을 고려해서 구조를 선택해야 합니다.

**Comment by juhee77** [comment]
와 설명 자세하게 해주셔서 감사합니다!!! 역시 희건님!!

**Comment by dlrjs2360** [comment]
ㅋㅋㅋㅋㅋㅋㅋ감사해용. 다른 이슈도 두 개 더 있는데 읽어보시구 질문있으시면 남겨주세용.
