### ISSUE TITLE
[💡Question] 2주차_p93_더 중요한 인덱스 사용 조건

### ISSUE THREAD

**Issue by ranunclulus** [code-appender/sql-tuning-level-up#12]
### ❓이런 내용이 궁금해요.

> 인덱스 선두 컬럼이 조건절에 있어야 함
-> 이 말이 인덱스로 쓰이는 특성이 리프 블록을 나누는 조건절로 사용되어야 한다는 말이 맞나요?!

**Comment by dlrjs2360** [comment]
"인덱스로 쓰이는 특성이 리프 블록을 나누는 조건절로 사용되어야 한다"는 결과적으로 비슷하지만 제가 생각하는 의미와는 조금 다른 말인 것 같습니다. 

정확히는 `'인덱스 리프 블록'을 정렬하고 나누는 기준이 '인덱스 컬럼'이며 인덱스 컬럼 중에서도 가장 첫 번째 기준인 '인덱스 선두 컬럼이 조건절에 등장'해야 한다`라고 생각합니다.

![image](https://github.com/code-appender/sql-tuning-level-up/assets/81156109/ab0c1f87-0383-4229-9dbc-d8922d4f5d3d)

위 그림은 책에 나오는 [ 그림 2-13 ] 예시입니다.

`인덱스 선두 컬럼`은 소속팀이며 `인덱스 리프 블록`들을 보면 소속팀을 기준으로 정렬된 것을 바로 확인할 수 있습니다. 

다음과 같은 SQL은 Index Range Scan이 발생할 수 있는 조건을 만족합니다.
```sql
SELECT 사원번호, 소속팀, 연령
FROM 사원
WHERE 소속팀='경영지원'
```

조건절에 인덱스 선두 컬럼인 소속팀이 등장했습니다. 

인덱스 리프 블록을 정렬하는 첫 번째 기준이 나타남에 따라 그림에서 보이는 첫 번째 인덱스 리프 블록 중에서도 두 번째 엔트리까지만 탐색할 수 있도록 "스캔 시작점"과 "스캔 끝점"을 알 수 있습니다.
왜냐하면 소속팀을 기준으로 정렬되었기 때문에 다른 인덱스 리프 블록에는 경영지원팀이 있을 수가 없기 떄문이죠.

하지만 만약 다음과 같은 SQL을 실행하면 어떻게 될까요?
```sql
SELECT 사원번호, 소속팀, 연령
FROM 사원
WHERE 사원명='홍길동'
```

조건절에 인덱스 선두 컬럼(=소속팀)이 등장하지 않았습니다. 

홍길동이라는 이름은 경영지원팀, 마케팅팀, 생산팀,,, 등 여러 팀에 분포될 수 있기 때문에 특정되지 않는 여러 리프 노드 블록에 찾고자 하는 데이터가 분포하게 됩니다. 

따라서 인덱스의 일정 범위를 스캔하는 Index Range Scan이 불가능하며 모든 인덱스 리프 블록을 탐색해야 하는 것입니다.
