### ISSUE TITLE
[💡Question] 4주차_176p_스캔

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-tuning-level-up#32]
### ❓이런 내용이 궁금해요.

스캔의 시작점을 찾기 위해 조건절을 사용하고 스캔량을 줄임으로써 성능을 향상한다고 하는데 스캔의 시작점, 끝점을 찾는 과정과 조건에 맞는 데이터를 스캔하는 과정이 어떤 차이가 있는지 궁금합니다. 끝점은 스캔을 멈출 수가 있지만 시작점은 시작점을 찾기까지의 과정도 스캔량에 포함되는 것이 아닌가 라는 생각이 들었습니다.

예를들어, 176p [그림 3-21]에서 C1='B' AND C2=3인 조건에 따라 스캔 시작점(2번 리프 블록의 4번 데이터)을 찾는 과정이 존재하는데 이 스캔시작점을 찾을 때도 리프블록안의 데이터를 조건절과 비교하는 과정(4번 데이터까지 이동하므로 4번의 비교)이 필요할텐데 이 시작점도 스캔량을 줄이는데에 역할을 할 수 있는 것인가요?

_질문이 조금 어려울 수 있으니 이해가 어려우시면 코멘트를 남겨주십숑.._

**Comment by YunByungil** [comment]
질문을 제대로 이해를 못한 것도 있는데,,,,, 내용 자체가 어려워서 답변을 못하겠습니다.. 이거는 오늘 모여서 같이 얘기해보는 것이 어떨까요?
