### ISSUE TITLE
[💡Question] 4주차_212p_액세스 조건

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-tuning-level-up#35]
### ❓이런 내용이 궁금해요.

211p 쿼리는 세 컬럼이 모두 액세스 조건이고 LIKE 연산자를 사용하면 액세스 조건이던 '상품명'이 필터 조건으로 바뀌는 이유를 조금 쉽게 설명해주시면 감사하겠습니당.

**Comment by YunByungil** [comment]
단순하게 선행 컬럼이 = 조건이 아니면 그 이후 조건들은 전부 필터 조건으로 바뀐다고 합니다.

가운데 컬럼 조건이 LIKE이기 때문에 가운데 컬럼을 기준으로 액세스 조건이 적용되고, 나머지는 필터 조건으로 검색합니다.
