### ISSUE TITLE
[💡Question] 4주차_p231_데이터를 일일히 지워줘야 하는 이유 

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-tuning-level-up#36]
### ❓이런 내용이 궁금해요.

>
데이터를 지울 때도 마찬가지다. 여섯 개 인덱스에서 레코드를 일일이 찾아 지워줘야 한다.
에서 왜 각각의 인덱스의 레코드를 일일히 지워줘야 하나요? (어떤 경우인가요?)

**Comment by YunByungil** [comment]
인덱스가 적용된 컬럼에 INSERT, UPDATE, DELETE가 수행된다면 각각 다음과 같은 연산을 추가적으로 해주어야 하며 그에 따른 오버헤드가 발생합니다.

따라서 추가된 데이터에 따라 인덱스 테이블에 값을 넣어주거나 삭제해야되기 때문에 일일이 찾아 지워줘야 합니다.
