### ISSUE TITLE
[💡Question] 5주차_p78_일반적으로 인덱스 스캔후 왜 테이블을 액세스 하는것인지

### ISSUE THREAD

**Issue by juhee77** [code-appender/sql-tuning-level-up#43]
### ❓이런 내용이 궁금해요.

>
78페이지의 마지막 쯤 `일반적으로 인덱스 스캔 후 테이블을 액세스 한다`라는 이야기가 있는데 이는  
`검색 조건` 및 `찾으려고 하는 데이터의 컬럼`이 모두 생성된 인덱스 내에 있는 경우만 테이블에 접근하지 않고 나머지의 경우는 데이터를 확인하기 위해 테이블에 접근한다는 이야기가 맞을까요?

**Comment by dlrjs2360** [comment]
### 간단요약
맞습니다! 정확히는 테이블에 접근하지 않는 경우는 `커버링 인덱스`를 사용하는 경우이고 일반적으로는 인덱스 스캔 후 테이블에 액세스하게 됩니다.

<br>

### 커버링 인덱스
커버링 인덱스한 쿼리를 충족하는데 필요한 모든 데이터를 갖는 인덱스를 뜻합니다.
쿼리를 충족한다는 것은 SELECT, WHERE, ORDER BY 등 쿼리에서 사용되는 모든 컬럼이 인덱스 컬럼 안에 포함된다는 것입니다.

### 커버링 인덱스 예시
예시를 하나 보겠습니다.
```sql
select id
from user
where id = 1;
```
위의 쿼리는 id가 PK임을 이용하여 커버링 인덱스를 사용한 경우입니다. 

![img1 daumcdn](https://github.com/code-appender/sql-tuning-level-up/assets/81156109/d4b6338c-988e-4583-b1d6-7d74c8ad512b)
위와 같이 커버링 인덱스를 사용하면 실행계획의 Extra 부분에 Using Index라는 내용이 표시됩니다.

<br>

### 복합 인덱스와 커버링 인덱스
조금 더 복잡한 예시를 보자면,
```sql
CREATE INDEX idx_email_first_name ON test2(email, first_name);

explain
select 
	email, first_name
from 
	user
where 
	first_name = 'Adrian';
```

위의 경우에는 복합 인덱스로 구성되었으며 조회 쿼리에 나오는 모든 컬럼이 인덱스에 포함됩니다.

이 실행계획을 살펴보면 새로운 내용이 추가되었음을 확인할 수 있는데

![img1 daumcdn](https://github.com/code-appender/sql-tuning-level-up/assets/81156109/aa4bf4c0-2c3f-4c41-98ec-f1b96701913d)
Extra를 보면 `Using where; Using Index`라는 문구를 찾을 수 있습니다.
이는 data를 찾을 때 where 조건을 사용했지만 type이 index이므로 index를 풀스캔했다는 것을 의미합니다.
풀스캔했지만 Index만을 스캔했기 때문에 Disk I/O 없이 빠른 속도로 조회가 가능했습니다.

<br>

### 복합 인덱스 + PK로 커버링 인덱스는 불가능하다.
위에서 설명한 두 가지 예시를 한 번에 합쳐보겠습니다.
```sql
explain
select 
email, first_name
from test2
where email = 'amckeandrq@businessinsider.com'
and first_name = 'Adrian'
and id = 2;
```
이번에는 pk를 포함하지 않는 인덱스와 pk인 ID를 함께 사용하는 쿼리를 살펴보겠습니다.

![img1 daumcdn](https://github.com/code-appender/sql-tuning-level-up/assets/81156109/5c2cacc0-7c96-4552-b4fe-e27e35628a8d)

결과는 Extra 가 Using where 나 Using index 가 아닌 null 로 레코드를 직접 읽었다고 유추할 수 있습니다.

이는 id와 복합인덱스인 email+first_name 중 id를 key로 설정하여 쿼리를 실행했음을 의미합니다.

<br>

### 복합 인덱스 + PK로 커버링 인덱스는 가능하다.
```sql
explain
select 
id, email, first_name
from test2
where email = 'amckeandrq@businessinsider.com'
and first_name = 'Adrian';
```
이번에는 위와 비슷한 상황이지만 where절이 아닌 select 절에 pk를 사용해보겠습니다.

![img1 daumcdn](https://github.com/code-appender/sql-tuning-level-up/assets/81156109/9deb3009-556a-4ff9-8810-da989d3b587f)

결과는 커버링 인덱스가 가능했습니다.

두 쿼리 모두 복합 인덱스에 PK를 포함시키지 않고 PK가 사용되는 공간을 바꿨을 뿐인데 결과가 극명하게 차이가 났습니다.

이는 Index Extension이라는 인덱스의 확장성으로 인한 결과인데 B+Tree 구조와 연관되어 투머치하게 복잡해지기에 이후에 책에서 등장하기를 바라면서...여기서 멈추겠습니다.

<br>

#### 참고자료
> https://velog.io/@boo105/%EC%BB%A4%EB%B2%84%EB%A7%81-%EC%9D%B8%EB%8D%B1%EC%8A%A4
> 
> https://liltdevs.tistory.com/194
