### ISSUE TITLE
[💡Question] 5주차_224p_Dynamic SQL

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-tuning-level-up#45]
### ❓이런 내용이 궁금해요.

> "Dynamic SQL에 옵티마이저 힌트를 명시하면 동적으로 구성된 조건절과 서로 상춤함으로 인해 오히려 성능 문제를 야기할 수 있다."

이 말이 잘 이해가 안됩니다. 동적 쿼리를 사용할 떄 특정 인덱스를 사용하도록 유도하는 힌트를 명시하면 동적으로 구성된 조건절과 상충한다는 것이 어떤 의미일까요..

**Comment by YunByungil** [comment]
옵티마이저 힌트를 특정 쿼리에 맞게 구성해두었는데 쿼리가 동적으로 바뀌었을 떄, 
옵티마이저 힌트로 최적화하기 위한 의도와 쿼리의 조건이 달라지니까 충돌할 수 있다는 얘기입니다.

개발자의 의도가 충돌할 수 있다고 이해하시면 될 것 같습니다.
