### ISSUE TITLE
[💡Question] 5주차_154p_다중 테이블 클러스터

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-tuning-level-up#46]
### ❓이런 내용이 궁금해요.

여러 테이블 레코드를 같은 블록에 저장하는 '다중 테이블 클러스터'는 어떤 방식으로 동작하는지 궁금합니다. 간단한 소개 부탁드립니다.

**Comment by juhee77** [comment]
클러스터 : 테이블이나 인덱스처럼 저장공간을 지닌 Object입니다.

이때 단일 클러스터가 다음사진과 같이 하나의 값에 대하여 인덱싱 하였다면 
<img width="726" alt="image" src="https://github.com/code-appender/sql-tuning-level-up/assets/51548333/bd746b03-230b-4abb-b800-fa52c76c0883">

다중 클러스터는 책에 적힌것처럼 단위 클러스터에 2개 이상의 테이블 데이터를 함께 저장하여 같은 저장소에 저장되게 합니다. 이를 통해 테이블 조인 속도를 향상 시킬 수 있습니다
<img width="719" alt="image" src="https://github.com/code-appender/sql-tuning-level-up/assets/51548333/24aed211-9491-431f-9a1c-59e7a6b3e23f">



[참고](https://zzanggoo.tistory.com/94)
