### ISSUE TITLE
[💡Question] 5주차_47p_시퀀셜 액세스vs랜덤 액세스

### ISSUE THREAD

**Issue by YunByungil** [code-appender/sql-tuning-level-up#47]
### ❓이런 내용이 궁금해요.

>
시퀀셜 액세스와 랜덤 액세스가 정확이 어떻게 블록을 읽는지 이해가 안 됩니다.
블록을 읽는다는게 테이블을 select 한다는 의미인가요?

**Comment by ranunclulus** [comment]
만약에 select 쿼리를 실행해서 데이터F~데이터I까지를 읽어야 한다고 가정하겠습니다. 각각의 데이터는 아래처럼 블록 단위로 저장되어 있습니다.

블록 1 - 데이터A, 데이터B, 데이터C
블록 2 - 데이터D, 데이터E, 데이터F
블록 3 - 데이터G, 데이터H, 데이터I

이때 만약 시퀀셜 액세스를 한다면 블록 1부터 차례차례 읽다가 F가 등장하는 블록 2부터 값을 리턴하게 됩니다. 데이터 양이 많을수록 시퀀셜 액세스의 비용이 증가하는 경우도 있습니다. 이럴 때 적절한 인덱스 처리를 통해 블록 2부터 접근해서 내가 원하는 데이터를 바로 읽을 수 있도록 하는 방법이 랜덤 액세스입니다. 하지만 만약 데이터가 내가 읽고자 하는 순서대로 정렬되어 저장되어 있지 않으면, 예를 들어 데이터A, 데이터 D, 데이터G를 읽어서 각각 다른 블록에 액세스해야 하는 경우라면 랜덤 액세스가 많은 것이 더 많은 비용을 초래할 수 있습니다!

**Comment by juhee77** [comment]
https://sas-study.tistory.com/448
