### ISSUE TITLE
[💡Question] 1주차_65p_래치와 락

### ISSUE THREAD

**Issue by dlrjs2360** [code-appender/sql-tuning-level-up#5]
### ❓이런 내용이 궁금해요.

일반적으로 사용하는 Lock 알고리즘과 latch의 차이점이 있나요? 책으로만 봤을 때는 일반적인 Lock과 다를게 없어보이는데 단순히 해시 체인에 사용하는 Lock 알고리즘을 Latch라고 하는 것인지 Latch만의 알고리즘이 따로 존재하는 것인지 궁금합니당.

**Comment by ranunclulus** [comment]
<img width="579" alt="image" src="https://github.com/code-appender/sql-tuning-level-up/assets/87214089/8ecbe749-699a-4356-81b6-d5acb67e7bcd">
